package HW;

public class AreaCodeListing {
	private String[] validCodes = new String[] { "201", "202", "203", "204", "205", "206", "207", "208", "209", "210",
			"211", "212", "213", "214", "215", "216", "217", "218", "219", "220", "223", "224", "225", "226", "228",
			"229", "231", "234", "236", "239", "240", "242", "246", "248", "250", "251", "252", "253", "254", "256",
			"260", "262", "264", "267", "268", "269", "270", "272", "276", "278", "281", "283", "284", "289", "301",
			"302", "303", "304", "305", "306", "307", "308", "309", "310", "311", "312", "313", "314", "315", "316",
			"317", "318", "319", "320", "321", "323", "325", "330", "331", "332", "334", "336", "337", "339", "340",
			"341", "343", "345", "346", "347", "351", "352", "360", "361", "365", "369", "380", "385", "386", "401",
			"402", "403", "404", "405", "406", "407", "408", "409", "410", "411", "412", "413", "414", "415", "416",
			"417", "418", "419", "423", "424", "425", "430", "431", "432", "434", "435", "437", "438", "440", "441",
			"442", "443", "450", "456", "458", "464", "469", "470", "473", "475", "478", "479", "480", "481", "484",
			"500", "501", "502", "503", "504", "505", "506", "507", "508", "509", "510", "511", "512", "513", "514",
			"515", "516", "517", "518", "519", "520", "530", "539", "540", "541", "548", "551", "555", "557", "559",
			"561", "562", "563", "564", "567", "570", "571", "573", "574", "575", "579", "580", "581", "585", "586",
			"587", "600", "601", "602", "603", "604", "605", "606", "607", "608", "609", "610", "611", "612", "613",
			"614", "615", "616", "617", "618", "619", "620", "623", "626", "627", "628", "629", "630", "631", "636",
			"639", "641", "646", "647", "649", "650", "651", "657", "660", "661", "662", "664", "667", "669", "670",
			"671", "678", "679", "681", "682", "684", "689", "700", "701", "702", "703", "704", "705", "706", "707",
			"708", "709", "710", "711", "712", "713", "714", "715", "716", "717", "718", "719", "720", "721", "724",
			"725", "727", "731", "732", "734", "737", "740", "743", "747", "754", "757", "758", "760", "762", "763",
			"764", "765", "767", "769", "770", "772", "773", "774", "775", "778", "779", "780", "781", "782", "784",
			"785", "786", "787", "800", "801", "802", "803", "804", "805", "806", "807", "808", "809", "810", "811",
			"812", "813", "814", "815", "816", "817", "818", "819", "822", "825", "828", "829", "830", "831", "832",
			"833", "835", "843", "844", "845", "847", "848", "849", "850", "855", "856", "857", "858", "859", "860",
			"862", "863", "864", "865", "866", "867", "868", "869", "870", "872", "873", "876", "877", "878", "880",
			"881", "882", "888", "898", "900", "901", "902", "903", "904", "905", "906", "907", "908", "909", "910",
			"911", "912", "913", "914", "915", "916", "917", "918", "919", "920", "925", "927", "928", "929", "931",
			"935", "936", "937", "939", "940", "941", "947", "949", "951", "952", "954", "956", "957", "959", "970",
			"971", "972", "973", "975", "976", "978", "979", "980", "984", "985", "989", "999" };
	private String[] validDesc = new String[] { "N New Jersey: Jersey City, Hackensack (see split 973, overlay 551)",
			"Washington, D.C.", "Connecticut: Fairfield County and New Haven County; Bridgeport, New Haven (see 860)",
			"Canada: Manitoba (see overlay 431)",
			"Central Alabama (including Birmingham; excludes the southeastern corner of Alabama and the deep south; see splits 256 and 334)",
			"W Washington state: Seattle and Bainbridge Island (see splits 253, 360, 425; overlay 564)", "Maine",
			"Idaho", "Cent. California: Stockton (see split 559)", "S Texas: San Antonio (see also splits 830, 956)",
			"Local community info / referral services",
			"New York City, New York (Manhattan; see ovelays 332, 646, 917; split 718)",
			"S California: Los Angeles (see 310, 323, 626, 818)", "Texas: Dallas Metro (overlays 469/972)",
			"SE Pennsylvania: Philadelphia (see overlays 267)", "Cleveland (see splits 330, 440)",
			"Cent. Illinois: Springfield", "N Minnesota: Duluth", "NW Indiana: Gary (see split 574, 260)",
			"SE and Central Ohio (outside Columbus; overlaid on 740)",
			"E Pennsylvania: Gettysburg, Harrisburg, Lancaster, Lebanan, and York (overlays 223, eff 8/2017)",
			"Northern NE Illinois: Evanston, Waukegan, Northbrook (overlay on 847, eff 1/5/02)",
			"Louisiana: Baton Rouge, New Roads, Donaldsonville, Albany, Gonzales, Greensburg, Plaquemine, Vacherie (split from 504)",
			"Canada: SW Ontario: Windsor (overlays 519, 548)",
			"S Mississippi (coastal areas, Biloxi, Gulfport; split from 601)",
			"SW Georgia: Albany (split from 912; see also 478; perm 8/1/00)",
			"W Michigan: Northwestern portion of lower Peninsula; Traverse City, Muskegon, Cheboygan, Alanson",
			"NE Ohio: Canton, Akron (overlaid on 330; perm 10/30/00)", "Canada: British Columbia (see 250, 604)",
			"Florida (Lee, Collier, and Monroe Counties, excl the Keys; see 305; eff 3/11/02; mand 3/11/03)",
			"W Maryland: Silver Spring, Frederick, Gaithersburg (overlay, see 301)", "Bahamas", "Barbados",
			"Michigan: Oakland County, Pontiac (split from 810; see overlay 947)",
			"Canada: British Columbia (see 236, 604)",
			"S Alabama: Mobile and coastal areas, Jackson, Evergreen, Monroeville (split from 334, eff 6/18/01; see also 205, 256)",
			"E North Carolina (Rocky Mount; split from 919)",
			"Washington: South Tier - Tacoma, Federal Way (split from 206, see also 425; overlay 564)",
			"Central Texas (Waco, Stephenville; split, see 817, 940)",
			"E and N Alabama (Huntsville, Florence, Gadsden; split from 205; see also 334)",
			"NE Indiana: Fort Wayne (see 219)",
			"SE Wisconsin: counties of Kenosha, Ozaukee, Racine, Walworth, Washington, Waukesha (split from 414)",
			"Anguilla (split from 809)", "SE Pennsylvania: Philadelphia (see 215)",
			"Antigua and Barbuda (split from 809)",
			"SW Michigan: Kalamazoo, Saugatuck, Hastings, Battle Creek, Sturgis to Lake Michigan (split from 616)",
			"W Kentucky: Bowling Green, Paducah (split from 502)",
			"NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; overlaid on 570)",
			"S and SW Virginia: Bristol, Stuart, Martinsville (split from 540; perm 9/1/01, mand 3/16/02)",
			"Michigan (overlaid on 734, SUSPENDED)", "Texas: Houston Metro (split 713; overlay 832, 346)",
			"SW Ohio: Cincinnati (cancelled: overlaid on 513)", "British Virgin Islands (split from 809)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto -- overlaid on 905)",
			"W Maryland: Silver Spring, Frederick, Camp Springs, Prince George's County (see 240)", "Delaware",
			"Central Colorado: Denver (see 970, also 720 overlay)", "West Virginia (see overlay 681)",
			"SE Florida: Miami, the Keys (see 786, 954; 239)", "Canada: Saskatchewan (see overlay 639)", "Wyoming",
			"W Nebraska: North Platte", "W Cent. Illinois: Peoria",
			"S California: Beverly Hills, West Hollywood, West Los Angeles (see split 562; overlay 424)",
			"Reserved for special applications",
			"Illinois: Chicago (downtown only -- in the loop; see 773; overlay 872)",
			"Michigan: Detroit and suburbs (see 734, overlay 679)",
			"SE Missouri: St Louis city and parts of the metro area only (see 573, 636, overlay 557)",
			"N Cent. New York: Syracuse", "S Kansas: Wichita (see split 620)", "Cent. Indiana: Indianapolis (see 765)",
			"N Louisiana: Shreveport, Ruston, Monroe, Alexandria (see split 337)",
			"E Iowa: Cedar Rapids (see split 563)",
			"Cent. Minnesota: Saint Cloud (rural Minn, excl St. Paul/Minneapolis)",
			"Florida: Brevard County, Cape Canaveral area; Metro Orlando (split from 407)",
			"S California: Los Angeles (outside downtown: Hollywood; split from 213)",
			"Central Texas: Abilene, Sweetwater, Snyder, San Angelo (split from 915)",
			"NE Ohio: Akron, Canton, Youngstown; Mahoning County, parts of Trumbull/Warren counties (see splits 216, 440, overlay 234)",
			"W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlaid on 630; eff 7/07)",
			"New York City, New York (Manhattan; overlaid on 212, 646, 917)",
			"S Alabama: Auburn/Opelika, Montgomery and coastal areas (part of what used to be 205; see also 256, split 251)",
			"Cent. North Carolina: Greensboro, Winston-Salem, High Point (split from 910; see overlay 743)",
			"SW Louisiana: Lake Charles, Lafayette (see split 318)",
			"Massachusetts: Boston suburbs, to the south and west (see splits 617, 508; overlaid on 781, eff 5/2/01)",
			"US Virgin Islands (see also 809)", "(overlay on 510; SUSPENDED)",
			"Canada: SE Ontario: Ottawa (overlaid on 613)", "Cayman Islands",
			"Mid SE Texas: central Houston (overlaid on 713, 281, and 832)",
			"New York City, New York (overlay for 718: NYC area, except Manhattan)",
			"Massachusetts: north of Boston to NH, 508, and 781 (overlaid on 978, eff 4/2/01)",
			"Florida: Gainesville area, Ocala, Crystal River (split from 904)",
			"W Washington State: Olympia, Bellingham (area circling 206, 253, and 425; split from 206; see overlay 564)",
			"S Texas: Corpus Christi (split from 512; eff 2/13/99)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (overlaid on 905)",
			"Solano County (perm 12/2/00, mand 6/2/01)", "Ohio: Columbus (overlaid on 614; assigned but not in use)",
			"Utah: Salt Lake City Metro (split from 801, eff 3/30/02 POSTPONED; see also 435)",
			"N central Florida: Lake City (split from 904, perm 2/15/01, mand 11/5/01)", "Rhode Island",
			"E Nebraska: Omaha, Lincoln", "Canada: Southern Alberta (see 587, 780, 825, 867)",
			"N Georgia: Atlanta and suburbs (see overlay 678, split 770)", "W Oklahoma: Oklahoma City (see 580)",
			"Montana", "Central Florida: Metro Orlando (see overlay 689, eff 7/02; split 321)",
			"Cent. Coastal California: San Jose (see overlay 669)",
			"SE Texas: Galveston, Port Arthur, Beaumont (splits 936, 979)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (see overlays 443, 667)",
			"Reserved for special applications", "W Pennsylvania: Pittsburgh (see split 724, overlay 878)",
			"W Massachusetts: Springfield", "SE Wisconsin: Milwaukee County (see splits 920, 262)",
			"California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (see 650 split; 628 overlay, eff 2/2015)",
			"Canada: S Cent. Ontario: Toronto (see overlays 437, 647)", "SW Missouri: Springfield",
			"Canada: NE Quebec: Quebec (see overlay 581)", "NW Ohio: Toledo (see overlay 567, perm 1/1/02)",
			"E Tennessee, except Knoxville metro area: Chattanooga, Bristol, Johnson City, Kingsport, Greeneville (see split 865; part of what used to be 615)",
			"S California: Los Angeles (see split 562; overlaid on 310 mand 7/26/06)",
			"Washington: North Tier - Everett, Bellevue (split from 206, see also 253; overlay 564)",
			"NE Texas: Tyler (overlaid on 903, eff 7/20/02)", "Canada: Manitoba (overlaid on 204; eff 11/12)",
			"W Texas: Big Spring, Midland, Odessa (split from 915, eff 4/5/03)",
			"E Virginia: Charlottesville, Lynchburg, Danville, South Boston, and Emporia (split from 804, eff 6/1/01; see also 757)",
			"Rural Utah outside Salt Lake City metro (see split 801)",
			"Canada: S Cent. Ontario: Toronto (overlaid on 416)",
			"Canada: SW Quebec: Montreal city (overlaid on 514, [delayed until 6/06] eff 10/10/03, mand 2/7/04)",
			"Ohio: Cleveland metro area, excluding Cleveland (split from 216, see also 330)",
			"Bermuda (part of what used to be 809)",
			"Far north suburbs of San Diego (Oceanside, Escondido; overlaid on 760)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, see overlay 667)",
			"Canada: Southeastern Quebec; suburbs outside metro Montreal (see overlay 579)", "Inbound International",
			"Oregon: Eugene, Medford (overlaid on 541)",
			"Illinois: south suburbs of Chicago (see 630; overlaid on 708)", "Texas: Dallas Metro (overlays 214/972)",
			"Georgia: Greater Atlanta Metropolitan Area (overlaid on 404/770/678; mand 9/2/01)",
			"Grenada (\"new\" -- split from 809)",
			"Connecticut: New Haven, Greenwich, southwestern (postponed; was perm 1/6/01; mand 3/1/01???)",
			"Central Georgia: Macon (split from 912; see also 229; perm 8/1/00; mand 8/1/01)",
			"NW Arkansas: Fort Smith, Fayetteville, Springdale, Bentonville (SPLIt from 501, perm 1/19/02, mand 7/20/02)",
			"Arizona: East Phoenix (see 520; also Phoenix split 602, 623)",
			"Canada: NE Quebec: Quebec (see overlay 418)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see 610)",
			"Personal Communication Service", "Central Arkansas: Little Rock, Hot Springs, Conway (see split 479)",
			"N Central Kentucky: Louisville (see 270)", "Oregon (see 458, 541, 971)",
			"E Louisiana: New Orleans metro area (see splits 225, 985)",
			"North central and northwestern New Mexico (Albuquerque, Santa Fe, Los Alamos; see split 575, eff 10/07/07)",
			"Canada: New Brunswick", "S Minnesota: Rochester, Mankato, Worthington",
			"Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlay 774)",
			"E and Central Washington state: Spokane, Yakima, Walla Walla, Ellensburg",
			"California: Oakland, East Bay (see 925)", "Nationwide travel information",
			"S Texas: Austin (see split 361; overlay 737, perm 11/10/01)",
			"SW Ohio: Cincinnati (see split 937; overlay 283 cancelled)",
			"Canada: SW Quebec: Montreal city (see overlay 438, eff 10/10/03, mand 2/7/04)",
			"Cent. Iowa: Des Moines (see split 641)", "New York: Nassau County, Long Island; Hempstead (see split 631)",
			"Cent. Michigan: Lansing (see split 989)", "NE New York: Albany",
			"Canada: SW Ontario: Windsor (see overlay 226, 548)",
			"SE Arizona: Tucson area (split from 602; see split 928)",
			"NE California: Eldorado County area, excluding Eldorado Hills itself: incl cities of Auburn, Chico, Redding, So. Lake Tahoe, Marysville, Nevada City/Grass Valley (split from 916)",
			"E Oklahoma: Tulsa area (overlaid on 918)",
			"Western and Southwest Virginia: Shenandoah and Roanoke valleys: Fredericksburg, Harrisonburg, Roanoke, Salem, Lexington and nearby areas (see split 276; split from 703)",
			"Oregon: Eugene, Medford (split from 503; 503 retains NW part [Portland/Salem], all else moves to 541; eastern oregon is UTC-7). Also serves small part of northern California (NE corner of Del Norte County). (See overlay 458.)",
			"Canada: Southwestern Ontario (London, Sarnia, Kitchener-Waterloo and Brantford; overlaid on 226, 519)",
			"N New Jersey: Jersey City, Hackensack (overlaid on 201)", "Reserved for directory assistance applications",
			"SE Missouri: St Louis metro area only (cancelled: overlaid on 314)",
			"Central California: Fresno (split from 209)",
			"S. Central Florida: Palm Beach County (West Palm Beach, Boca Raton, Vero Beach; see split 772, eff 2/11/02; mand 11/11/02)",
			"California: Long Beach (split from 310 Los Angeles)",
			"E Iowa: Davenport, Dubuque (split from 319, eff 3/25/01)",
			"W Washington State: Olympia, Bellingham (overlaid on 360; see also 206, 253, 425; assigned but not in use)",
			"NW Ohio: Toledo (overlaid on 419, perm 1/1/02)",
			"NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; see overlay 272)",
			"Northern Virginia: Arlington, McLean, Tysons Corner (to be overlaid on 703 3/1/00; see earlier split 540)",
			"SE Missouri: excluding St Louis metro area, includes Central/East Missouri, area between St. Louis and Kansas City",
			"N Indiana: Elkhart, South Bend (split from 219)",
			"New Mexico (Las Cruces, Alamogordo, Roswell; split from 505, eff 10/07/07)",
			"Canada: Southeastern Quebec; suburbs outside metro Montreal (overlaid on 450)",
			"W Oklahoma (rural areas outside Oklahoma City; split from 405)",
			"Canada: NE Quebec: Quebec (overlaid on 418)", "NW New York: Rochester (split from 716)",
			"Michigan: Macomb County (split from 810; perm 9/22/01, mand 3/23/02)",
			"Canada: Alberta (see 403, 780, 825)", "Canadian Services",
			"Mississippi: Meridian, Jackson area (see splits 228, 662; overlay 769)",
			"Arizona: Phoenix (see 520; also Phoenix split 480, 623)", "New Hampshire",
			"Canada: British Columbia: Greater Vancouver (overlay 778, perm 11/3/01; see 250)", "South Dakota",
			"E Kentucky: area east of Frankfort: Ashland (see 859)", "S Cent. New York: Ithaca, Binghamton; Catskills",
			"SW Wisconsin: Madison", "S New Jersey: Trenton (see 856)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see overlays 484, 835)",
			"Reserved for special applications",
			"Cent. Minnesota: Minneapolis (split from St. Paul, see 651; see splits 763, 952)",
			"Canada: SE Ontario: Ottawa (see overlay 343)", "SE Ohio: Columbus (see overlay 380)",
			"Northern Middle Tennessee: Nashville metro area (see 423, 931; see overlay 629, eff 2014)",
			"W Michigan: Holland, Grand Haven, Greenville, Grand Rapids, Ionia (see split 269)",
			"Massachusetts: greater Boston (see overlay 857)", "S Illinois: Centralia",
			"S California: San Diego (see split 760; overlay 858, 935)",
			"S Kansas: Wichita (split from 316; perm 2/3/01)",
			"Arizona: West Phoenix (see 520; also Phoenix split 480, 602)",
			"E S California: Pasadena (split from 818 Los Angeles)",
			"No longer in use [was Napa, Sonoma counties (perm 10/13/01, mand 4/13/02); now 707]",
			"California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (overlaid on 415, eff 2/2015)",
			"Northern Middle Tennessee: Nashville metro area (see 423, 931; overlaid on 615, eff 2014)",
			"W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlay 331)",
			"New York: Suffolk County, Long Island; Huntington, Riverhead (split 516)",
			"Missouri: W St. Louis metro area of St. Louis county, St. Charles County, Jefferson County area south (between 314 and 573)",
			"Canada: Saskatchewan (overlaid on 306)",
			"Iowa: Mason City, Marshalltown, Creston, Ottumwa (split from 515; perm 7/9/00)",
			"New York (overlaid on 212, 332, 917) NYC (mostly mobile)",
			"Canada: S Cent. Ontario: Toronto (overlaid on 416)", "Turks & Caicos Islands",
			"California: Peninsula south of San Francisco -- San Mateo County, parts of Santa Clara County (split from 415)",
			"Cent. Minnesota: St. Paul (split from Minneapolis, see 612)",
			"Northern and western Orange County (overlaid on 714)", "N Missouri (split from 816)",
			"California: N Los Angeles, Mckittrick, Mojave, Newhall, Oildale, Palmdale, Taft, Tehachapi, Bakersfield, Earlimart, Lancaster (split from 805)",
			"N Mississippi: Tupelo, Grenada (split from 601)", "Montserrat (split from 809)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, 443)",
			"Cent. Coastal California: San Jose (overlaid on 408; eff 10/20/2012)",
			"Commonwealth of the Northern Mariana Islands (CNMI, US Commonwealth)", "Guam",
			"N Georgia: metropolitan Atlanta (overlay; see 404, 770)",
			"Michigan: Dearborn area (overlaid on 313; assigned but not in use)", "West Virginia (overlaid on 304)",
			"Texas: Fort Worth areas (perm 10/7/00, mand 12/9/00)", "American Samoa",
			"Central Florida: Metro Orlando (see overlay 321; overlaid on 407, assigned but not in use)",
			"Interexchange Carrier Services", "North Dakota",
			"S. Nevada: Clark County, incl Las Vegas (overlay 725, eff 6/2014; see also 775)",
			"Northern Virginia: Arlington, McLean, Tysons Corner (see split 540; overlay 571)",
			"W North Carolina: Charlotte (see split 828, overlay 980)",
			"Canada: NE Ontario: Sault Ste. Marie/N Ontario: N Bay, Sudbury",
			"N Georgia: Columbus, Augusta (see overlay 762)",
			"NW California: Santa Rosa, Napa, Vallejo, American Canyon, Fairfield",
			"Illinois: southern and western suburbs of Chicago (see 630; overlay 464)",
			"Canada: Newfoundland and Labrador", "US Government", "Telecommunications Relay Services",
			"W Iowa: Council Bluffs", "Mid SE Texas: central Houston (split 281; overlay 346, 832)",
			"Northern and western Orange County (see split 949, overlay 657)",
			"N Wisconsin: Eau Claire, Wausau, Superior", "NW New York: Buffalo (see split 585)",
			"E Pennsylvania: Harrisburg (see split 570, overlay 223)",
			"New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 929)",
			"SE Colorado: Pueblo, Colorado Springs", "Central Colorado: Denver (overlaid on 303)",
			"Sint Maarten (used to be country code +599)",
			"SW Pennsylvania (areas outside metro Pittsburgh; split from 412)",
			"S. Nevada: Clark County, incl Las Vegas (overlaid on 702, eff 6/2014; see also 775)",
			"Florida Tampa Metro: Saint Petersburg, Clearwater (Pinellas and parts of Pasco County; split from 813)",
			"W Tennessee: outside Memphis metro area (split from 901, perm 2/12/01, mand 9/17/01)",
			"Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 848)",
			"SE Michigan: west and south of Detroit -- Ann Arbor, Monroe (split from 313)",
			"S Texas: Austin (overlaid on 512, suspended; see also 361)",
			"SE and Central Ohio (outside Columbus; split from 614; overlay 220)",
			"Cent. North Carolina: Greensboro, Winston-Salem, High Point (overlaid on 336)",
			"S California: Los Angeles, Agoura Hills, Calabasas, Hidden Hills, and Westlake Village (see 818; implementation suspended)",
			"Florida: Broward County area, incl Ft. Lauderdale (overlaid on 954; perm 8/1/01, mand 9/1/01)",
			"E Virginia: Tidewater / Hampton Roads area -- Norfolk, Virginia Beach, Chesapeake, Portsmouth, Hampton, Newport News, Suffolk (part of what used to be 804)",
			"St. Lucia (split from 809)",
			"California: San Diego North County to Sierra Nevada (split from 619; see overlay 442)",
			"N Georgia: Columbus, Augusta (overlaid on 706)",
			"Minnesota: Minneapolis NW (split from 612; see also 952)", "(overlay on 650; SUSPENDED)",
			"Indiana: outside Indianapolis (split from 317)", "Dominica (split from 809)",
			"Mississippi: Meridian, Jackson area (overlaid on 601; perm 7/19/04, mand 3/14/05)",
			"Georgia: Atlanta suburbs: outside of I-285 ring road (part of what used to be 404; see also overlay 678)",
			"S. Central Florida: St. Lucie, Martin, and Indian River counties (split from 561; eff 2/11/02; mand 11/11/02)",
			"Illinois: city of Chicago, outside the loop (see 312; overlay 872)",
			"Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlaid on 508, eff 4/2/01)",
			"N. Nevada: Reno (all of NV except Clark County area; see 702)",
			"Canada: British Columbia: Greater Vancouver (overlaid on 604, per 11/3/01; see also 250)",
			"NW Illinois: Rockford, Kankakee (overlaid on 815; eff 8/19/06, mand 2/17/07)",
			"Canada: Northern Alberta, north of Lacombe (see 403, 587, 825)",
			"Massachusetts: Boston surburbs, to the north and west (see splits 617, 508; overlay 339)",
			"Nova Scotia & Prince Edward Island (to be overlaid on 902, eff 11/30/14)",
			"St. Vincent & Grenadines (split from 809)", "N & W Kansas: Topeka (split from 913)",
			"SE Florida, Monroe County (Miami; overlaid on 305)", "Puerto Rico (see overlay 939, perm 8/1/01)",
			"US/Canada toll free (see 888, 877, 866, 855, 844, 833, 822)",
			"Utah: Salt Lake City Metro (see split 385, eff 3/30/02; see also split 435)", "Vermont",
			"South Carolina: Columbia, Aiken, Sumter (see 843, 864)", "E Virginia: Richmond (see splits 757, 434)",
			"S Cent. and Cent. Coastal California: Ventura County, Santa Barbara County: San Luis Obispo, Thousand Oaks, Carpinteria, Santa Barbara, Santa Maria, Lompoc, Santa Ynez Valley / Solvang (see 661 split)",
			"Panhandle Texas: Amarillo, Lubbock", "Canada: W Ontario: Thunder Bay region to Manitoba border", "Hawaii",
			"Dominican Republic (see splits 264, 268, 284, 340, 441, 473, 664, 758, 767, 784, 868, 876; overlay 829)",
			"E Michigan: Flint, Pontiac (see 248; split 586)", "Reserved for special applications",
			"S Indiana: Evansville, Cincinnati outskirts in IN, Columbus, Bloomington (mostly GMT-5)",
			"SW Florida: Tampa Metro (splits 727 St. Petersburg, Clearwater, and 941 Sarasota)",
			"Cent. Pennsylvania: Erie", "NW Illinois: Rockford, Kankakee (see overlay 779; eff 8/19/06, mand 2/17/07)",
			"N Missouri: Kansas City (see split 660, overlay 975)", "N Cent. Texas: Fort Worth area (see 254, 940)",
			"S California: Los Angeles: San Fernando Valley (see 213, 310, 562, 626, 747)",
			"NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (see split 867; see overlay 873)",
			"US/Canada toll free (proposed, may not be in use yet)", "Alberta (overlay; see 403, 587, 780)",
			"W North Carolina: Asheville (split from 704)",
			"Dominican Republic (perm 1/31/05; mand 8/1/05; overlaid on 809)",
			"Texas: region surrounding San Antonio (split from 210)",
			"California: central coast area from Santa Cruz through Monterey County",
			"Texas: Houston (overlay 713, 281, 346)", "US/Canada toll free (proposed, may not be in use yet)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (overlaid on 610, eff 5/1/01; see also 484)",
			"South Carolina, coastal area: Charleston, Beaufort, Myrtle Beach (split from 803)",
			"US/Canada toll free (proposed, may not be in use yet)",
			"New York: Poughkeepsie; Nyack, Nanuet, Valley Cottage, New City, Putnam, Dutchess, Rockland, Orange, Ulster and parts of Sullivan counties in New York's lower Hudson Valley and Delaware County in the Catskills (see 914; perm 6/5/00)",
			"Northern NE Illinois: northwestern suburbs of chicago (Evanston, Waukegan, Northbrook; see overlay 224)",
			"Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 732)",
			"Dominican Republic: Santo Domingo",
			"Florida panhandle, from east of Tallahassee to Pensacola (split from 904); western panhandle (Pensacola, Panama City) are UTC-6",
			"US/Canada toll free", "SW New Jersey: greater Camden area, Mt Laurel (split from 609)",
			"Massachusetts: greater Boston (overlaid on 617, eff 4/2/01)",
			"S California: San Diego (see split 760; overlay 619, 935)",
			"N and Central Kentucky: Lexington; suburban KY counties of Cincinnati OH metro area; Covington, Newport, Ft. Thomas, Ft. Wright, Florence (split from 606)",
			"Connecticut: areas outside of Fairfield and New Haven Counties (split from 203, overlay 959)",
			"N New Jersey: Newark Paterson Morristown (overlaid on 973)",
			"Florida: Lakeland, Polk County (split from 941)",
			"South Carolina, upstate area: Greenville, Spartanburg (split from 803)",
			"E Tennessee: Knoxville, Knox and adjacent counties (split from 423; part of what used to be 615)",
			"US/Canada toll free", "Canada: Yukon, Northwest Territories, Nunavut (split from 403/819)",
			"Trinidad and Tobago (\"new\" -- see 809)", "St. Kitts & Nevis",
			"Arkansas: areas outside of west/central AR: Jonesboro, etc",
			"Illinois: Chicago (downtown only -- in the loop; see 773; overlaid on 312 and 773)",
			"NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (overlaid on 819)",
			"Jamaica (split from 809)", "US/Canada toll free",
			"Pittsburgh, New Castle (overlaid on 412, perm 8/17/01, mand t.b.a.)", "Paid Toll-Free Service",
			"Paid Toll-Free Service", "Paid Toll-Free Service", "US/Canada toll free", "VoIP service",
			"US toll calls -- prices vary with the number called",
			"W Tennessee: Memphis metro area (see 615, 931, split 731)",
			"Canada: Nova Scotia, Prince Edward Island (see overlay 782)",
			"NE Texas: Tyler (see overlay 430, eff 7/20/02)", "N Florida: Jacksonville (see splits 352, 386, 850)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto -- see overlay 289, 365, splits 416, 647)",
			"Upper Peninsula Michigan: Sault Ste. Marie, Escanaba, Marquette (UTC-6 towards the WI border)", "Alaska",
			"Cent. New Jersey: Elizabeth, Basking Ridge, Somerville, Bridgewater, Bound Brook",
			"California: Inland empire: San Bernardino (see split 951), Riverside",
			"S Cent. North Carolina: Fayetteville, Wilmington (see 336)", "Emergency",
			"SE Georgia: Savannah (see splits 229, 478)", "Kansas: Kansas City area (see 785)",
			"S New York: Westchester County (see 845)", "W Texas: El Paso (see splits 325 eff 4/5/03; 432, eff 4/5/03)",
			"NE California: Sacramento, Walnut Grove, Lincoln, Newcastle and El Dorado Hills (split to 530)",
			"New York: New York City (cellular, see 646)", "E Oklahoma: Tulsa (see overlay 539)",
			"E North Carolina: Raleigh (see split 252, overlay 984)",
			"NE Wisconsin: Appleton, Green Bay, Sheboygan, Fond du Lac (from Beaver Dam NE to Oshkosh, Appleton, and Door County; part of what used to be 414)",
			"California: Contra Costa area: Antioch, Concord, Pleasanton, Walnut Creek (split from 510)",
			"Florida: Cellular coverage in Orlando area",
			"Central and Northern Arizona: Prescott, Flagstaff, Yuma (split from 520)",
			"New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 718)",
			"Middle Tennessee: semi-circular ring around Nashville (split from 615)",
			"S California: San Diego (see split 760; overlay 858, 619; assigned but not in use)",
			"SE Texas: Conroe, Lufkin, Nacogdoches, Crockett (split from 409, see also 979)",
			"SW Ohio: Dayton (part of what used to be 513)", "Puerto Rico (overlaid on 787, perm 8/1/01)",
			"N Cent. Texas: Denton, Wichita Falls (split from 254, 817)",
			"SW Florida: Sarasota and Manatee counties (part of what used to be 813; see split 863)",
			"Michigan: Oakland County (overlays 248, perm 5/5/01)",
			"California: S Coastal Orange County (split from 714)",
			"California: W Riverside County (split from 909; eff 7/17/04)",
			"Minnesota: Minneapolis SW, Bloomington (split from 612; see also 763)",
			"Florida: Broward County area, incl Ft. Lauderdale (part of what used to be 305, see overlay 754)",
			"Texas: Valley of Texas area; Harlingen, Laredo (split from 210)", "New Mexico (pending; region unknown)",
			"Connecticut: Hartford, New London (postponed; was overlaid on 860 perm 1/6/01; mand 3/1/01???)",
			"N and W Colorado (part of what used to be 303)",
			"Oregon: Metropolitan Portland, Salem/Keizer area, incl Cricket Wireless (see 503; perm 10/1/00)",
			"Texas: Dallas Metro (overlays 214/469)",
			"N New Jersey: Newark, Paterson, Morristown (see overlay 862; split from 201)",
			"N Missouri: Kansas City (overlaid on 816)", "Unassigned",
			"Massachusetts: north of Boston to NH (see split 978 -- this is the northern half of old 508; see overlay 351)",
			"SE Texas: Bryan, College Station, Bay City (split from 409, see also 936)",
			"North Carolina: (overlay on 704; perm 5/1/00, mand 3/15/01)",
			"E North Carolina: Raleigh (overlaid on 919, perm 8/1/01, mand 2/5/02 POSTPONED)",
			"E Louisiana: SE/N shore of Lake Pontchartrain: Hammond, Slidell, Covington, Amite, Kentwood, area SW of New Orleans, Houma, Thibodaux, Morgan City (split from 504; perm 2/12/01; mand 10/22/01)",
			"Upper central Michigan: Mt Pleasant, Saginaw (split from 517; perm 4/7/01)", "", "", "",
			"N New Jersey: Jersey City, Hackensack (see split 973, overlay 551)", "Washington, D.C.",
			"Connecticut: Fairfield County and New Haven County; Bridgeport, New Haven (see 860)",
			"Canada: Manitoba (see overlay 431)",
			"Central Alabama (including Birmingham; excludes the southeastern corner of Alabama and the deep south; see splits 256 and 334)",
			"W Washington state: Seattle and Bainbridge Island (see splits 253, 360, 425; overlay 564)", "Maine",
			"Idaho", "Cent. California: Stockton (see split 559)", "S Texas: San Antonio (see also splits 830, 956)",
			"Local community info / referral services",
			"New York City, New York (Manhattan; see ovelays 332, 646, 917; split 718)",
			"S California: Los Angeles (see 310, 323, 626, 818)", "Texas: Dallas Metro (overlays 469/972)",
			"SE Pennsylvania: Philadelphia (see overlays 267)", "Cleveland (see splits 330, 440)",
			"Cent. Illinois: Springfield", "N Minnesota: Duluth", "NW Indiana: Gary (see split 574, 260)",
			"SE and Central Ohio (outside Columbus; overlaid on 740)",
			"E Pennsylvania: Gettysburg, Harrisburg, Lancaster, Lebanan, and York (overlays 223, eff 8/2017)",
			"Northern NE Illinois: Evanston, Waukegan, Northbrook (overlay on 847, eff 1/5/02)",
			"Louisiana: Baton Rouge, New Roads, Donaldsonville, Albany, Gonzales, Greensburg, Plaquemine, Vacherie (split from 504)",
			"Canada: SW Ontario: Windsor (overlays 519, 548)",
			"S Mississippi (coastal areas, Biloxi, Gulfport; split from 601)",
			"SW Georgia: Albany (split from 912; see also 478; perm 8/1/00)",
			"W Michigan: Northwestern portion of lower Peninsula; Traverse City, Muskegon, Cheboygan, Alanson",
			"NE Ohio: Canton, Akron (overlaid on 330; perm 10/30/00)", "Canada: British Columbia (see 250, 604)",
			"Florida (Lee, Collier, and Monroe Counties, excl the Keys; see 305; eff 3/11/02; mand 3/11/03)",
			"W Maryland: Silver Spring, Frederick, Gaithersburg (overlay, see 301)", "Bahamas", "Barbados",
			"Michigan: Oakland County, Pontiac (split from 810; see overlay 947)",
			"Canada: British Columbia (see 236, 604)",
			"S Alabama: Mobile and coastal areas, Jackson, Evergreen, Monroeville (split from 334, eff 6/18/01; see also 205, 256)",
			"E North Carolina (Rocky Mount; split from 919)",
			"Washington: South Tier - Tacoma, Federal Way (split from 206, see also 425; overlay 564)",
			"Central Texas (Waco, Stephenville; split, see 817, 940)",
			"E and N Alabama (Huntsville, Florence, Gadsden; split from 205; see also 334)",
			"NE Indiana: Fort Wayne (see 219)",
			"SE Wisconsin: counties of Kenosha, Ozaukee, Racine, Walworth, Washington, Waukesha (split from 414)",
			"Anguilla (split from 809)", "SE Pennsylvania: Philadelphia (see 215)",
			"Antigua and Barbuda (split from 809)",
			"SW Michigan: Kalamazoo, Saugatuck, Hastings, Battle Creek, Sturgis to Lake Michigan (split from 616)",
			"W Kentucky: Bowling Green, Paducah (split from 502)",
			"NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; overlaid on 570)",
			"S and SW Virginia: Bristol, Stuart, Martinsville (split from 540; perm 9/1/01, mand 3/16/02)",
			"Michigan (overlaid on 734, SUSPENDED)", "Texas: Houston Metro (split 713; overlay 832, 346)",
			"SW Ohio: Cincinnati (cancelled: overlaid on 513)", "British Virgin Islands (split from 809)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto -- overlaid on 905)",
			"W Maryland: Silver Spring, Frederick, Camp Springs, Prince George's County (see 240)", "Delaware",
			"Central Colorado: Denver (see 970, also 720 overlay)", "West Virginia (see overlay 681)",
			"SE Florida: Miami, the Keys (see 786, 954; 239)", "Canada: Saskatchewan (see overlay 639)", "Wyoming",
			"W Nebraska: North Platte", "W Cent. Illinois: Peoria",
			"S California: Beverly Hills, West Hollywood, West Los Angeles (see split 562; overlay 424)",
			"Reserved for special applications",
			"Illinois: Chicago (downtown only -- in the loop; see 773; overlay 872)",
			"Michigan: Detroit and suburbs (see 734, overlay 679)",
			"SE Missouri: St Louis city and parts of the metro area only (see 573, 636, overlay 557)",
			"N Cent. New York: Syracuse", "S Kansas: Wichita (see split 620)", "Cent. Indiana: Indianapolis (see 765)",
			"N Louisiana: Shreveport, Ruston, Monroe, Alexandria (see split 337)",
			"E Iowa: Cedar Rapids (see split 563)",
			"Cent. Minnesota: Saint Cloud (rural Minn, excl St. Paul/Minneapolis)",
			"Florida: Brevard County, Cape Canaveral area; Metro Orlando (split from 407)",
			"S California: Los Angeles (outside downtown: Hollywood; split from 213)",
			"Central Texas: Abilene, Sweetwater, Snyder, San Angelo (split from 915)",
			"NE Ohio: Akron, Canton, Youngstown; Mahoning County, parts of Trumbull/Warren counties (see splits 216, 440, overlay 234)",
			"W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlaid on 630; eff 7/07)",
			"New York City, New York (Manhattan; overlaid on 212, 646, 917)",
			"S Alabama: Auburn/Opelika, Montgomery and coastal areas (part of what used to be 205; see also 256, split 251)",
			"Cent. North Carolina: Greensboro, Winston-Salem, High Point (split from 910; see overlay 743)",
			"SW Louisiana: Lake Charles, Lafayette (see split 318)",
			"Massachusetts: Boston suburbs, to the south and west (see splits 617, 508; overlaid on 781, eff 5/2/01)",
			"US Virgin Islands (see also 809)", "(overlay on 510; SUSPENDED)",
			"Canada: SE Ontario: Ottawa (overlaid on 613)", "Cayman Islands",
			"Mid SE Texas: central Houston (overlaid on 713, 281, and 832)",
			"New York City, New York (overlay for 718: NYC area, except Manhattan)",
			"Massachusetts: north of Boston to NH, 508, and 781 (overlaid on 978, eff 4/2/01)",
			"Florida: Gainesville area, Ocala, Crystal River (split from 904)",
			"W Washington State: Olympia, Bellingham (area circling 206, 253, and 425; split from 206; see overlay 564)",
			"S Texas: Corpus Christi (split from 512; eff 2/13/99)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (overlaid on 905)",
			"Solano County (perm 12/2/00, mand 6/2/01)", "Ohio: Columbus (overlaid on 614; assigned but not in use)",
			"Utah: Salt Lake City Metro (split from 801, eff 3/30/02 POSTPONED; see also 435)",
			"N central Florida: Lake City (split from 904, perm 2/15/01, mand 11/5/01)", "Rhode Island",
			"E Nebraska: Omaha, Lincoln", "Canada: Southern Alberta (see 587, 780, 825, 867)",
			"N Georgia: Atlanta and suburbs (see overlay 678, split 770)", "W Oklahoma: Oklahoma City (see 580)",
			"Montana", "Central Florida: Metro Orlando (see overlay 689, eff 7/02; split 321)",
			"Cent. Coastal California: San Jose (see overlay 669)",
			"SE Texas: Galveston, Port Arthur, Beaumont (splits 936, 979)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (see overlays 443, 667)",
			"Reserved for special applications", "W Pennsylvania: Pittsburgh (see split 724, overlay 878)",
			"W Massachusetts: Springfield", "SE Wisconsin: Milwaukee County (see splits 920, 262)",
			"California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (see 650 split; 628 overlay, eff 2/2015)",
			"Canada: S Cent. Ontario: Toronto (see overlays 437, 647)", "SW Missouri: Springfield",
			"Canada: NE Quebec: Quebec (see overlay 581)", "NW Ohio: Toledo (see overlay 567, perm 1/1/02)",
			"E Tennessee, except Knoxville metro area: Chattanooga, Bristol, Johnson City, Kingsport, Greeneville (see split 865; part of what used to be 615)",
			"S California: Los Angeles (see split 562; overlaid on 310 mand 7/26/06)",
			"Washington: North Tier - Everett, Bellevue (split from 206, see also 253; overlay 564)",
			"NE Texas: Tyler (overlaid on 903, eff 7/20/02)", "Canada: Manitoba (overlaid on 204; eff 11/12)",
			"W Texas: Big Spring, Midland, Odessa (split from 915, eff 4/5/03)",
			"E Virginia: Charlottesville, Lynchburg, Danville, South Boston, and Emporia (split from 804, eff 6/1/01; see also 757)",
			"Rural Utah outside Salt Lake City metro (see split 801)",
			"Canada: S Cent. Ontario: Toronto (overlaid on 416)",
			"Canada: SW Quebec: Montreal city (overlaid on 514, [delayed until 6/06] eff 10/10/03, mand 2/7/04)",
			"Ohio: Cleveland metro area, excluding Cleveland (split from 216, see also 330)",
			"Bermuda (part of what used to be 809)",
			"Far north suburbs of San Diego (Oceanside, Escondido; overlaid on 760)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, see overlay 667)",
			"Canada: Southeastern Quebec; suburbs outside metro Montreal (see overlay 579)", "Inbound International",
			"Oregon: Eugene, Medford (overlaid on 541)",
			"Illinois: south suburbs of Chicago (see 630; overlaid on 708)", "Texas: Dallas Metro (overlays 214/972)",
			"Georgia: Greater Atlanta Metropolitan Area (overlaid on 404/770/678; mand 9/2/01)",
			"Grenada (\"new\" -- split from 809)",
			"Connecticut: New Haven, Greenwich, southwestern (postponed; was perm 1/6/01; mand 3/1/01???)",
			"Central Georgia: Macon (split from 912; see also 229; perm 8/1/00; mand 8/1/01)",
			"NW Arkansas: Fort Smith, Fayetteville, Springdale, Bentonville (SPLIt from 501, perm 1/19/02, mand 7/20/02)",
			"Arizona: East Phoenix (see 520; also Phoenix split 602, 623)",
			"Canada: NE Quebec: Quebec (see overlay 418)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see 610)",
			"Personal Communication Service", "Central Arkansas: Little Rock, Hot Springs, Conway (see split 479)",
			"N Central Kentucky: Louisville (see 270)", "Oregon (see 458, 541, 971)",
			"E Louisiana: New Orleans metro area (see splits 225, 985)",
			"North central and northwestern New Mexico (Albuquerque, Santa Fe, Los Alamos; see split 575, eff 10/07/07)",
			"Canada: New Brunswick", "S Minnesota: Rochester, Mankato, Worthington",
			"Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlay 774)",
			"E and Central Washington state: Spokane, Yakima, Walla Walla, Ellensburg",
			"California: Oakland, East Bay (see 925)", "Nationwide travel information",
			"S Texas: Austin (see split 361; overlay 737, perm 11/10/01)",
			"SW Ohio: Cincinnati (see split 937; overlay 283 cancelled)",
			"Canada: SW Quebec: Montreal city (see overlay 438, eff 10/10/03, mand 2/7/04)",
			"Cent. Iowa: Des Moines (see split 641)", "New York: Nassau County, Long Island; Hempstead (see split 631)",
			"Cent. Michigan: Lansing (see split 989)", "NE New York: Albany",
			"Canada: SW Ontario: Windsor (see overlay 226, 548)",
			"SE Arizona: Tucson area (split from 602; see split 928)",
			"NE California: Eldorado County area, excluding Eldorado Hills itself: incl cities of Auburn, Chico, Redding, So. Lake Tahoe, Marysville, Nevada City/Grass Valley (split from 916)",
			"E Oklahoma: Tulsa area (overlaid on 918)",
			"Western and Southwest Virginia: Shenandoah and Roanoke valleys: Fredericksburg, Harrisonburg, Roanoke, Salem, Lexington and nearby areas (see split 276; split from 703)",
			"Oregon: Eugene, Medford (split from 503; 503 retains NW part [Portland/Salem], all else moves to 541; eastern oregon is UTC-7). Also serves small part of northern California (NE corner of Del Norte County). (See overlay 458.)",
			"Canada: Southwestern Ontario (London, Sarnia, Kitchener-Waterloo and Brantford; overlaid on 226, 519)",
			"N New Jersey: Jersey City, Hackensack (overlaid on 201)", "Reserved for directory assistance applications",
			"SE Missouri: St Louis metro area only (cancelled: overlaid on 314)",
			"Central California: Fresno (split from 209)",
			"S. Central Florida: Palm Beach County (West Palm Beach, Boca Raton, Vero Beach; see split 772, eff 2/11/02; mand 11/11/02)",
			"California: Long Beach (split from 310 Los Angeles)",
			"E Iowa: Davenport, Dubuque (split from 319, eff 3/25/01)",
			"W Washington State: Olympia, Bellingham (overlaid on 360; see also 206, 253, 425; assigned but not in use)",
			"NW Ohio: Toledo (overlaid on 419, perm 1/1/02)",
			"NE and N Central Pennsylvania: Wilkes-Barre, Scranton (see 717; see overlay 272)",
			"Northern Virginia: Arlington, McLean, Tysons Corner (to be overlaid on 703 3/1/00; see earlier split 540)",
			"SE Missouri: excluding St Louis metro area, includes Central/East Missouri, area between St. Louis and Kansas City",
			"N Indiana: Elkhart, South Bend (split from 219)",
			"New Mexico (Las Cruces, Alamogordo, Roswell; split from 505, eff 10/07/07)",
			"Canada: Southeastern Quebec; suburbs outside metro Montreal (overlaid on 450)",
			"W Oklahoma (rural areas outside Oklahoma City; split from 405)",
			"Canada: NE Quebec: Quebec (overlaid on 418)", "NW New York: Rochester (split from 716)",
			"Michigan: Macomb County (split from 810; perm 9/22/01, mand 3/23/02)",
			"Canada: Alberta (see 403, 780, 825)", "Canadian Services",
			"Mississippi: Meridian, Jackson area (see splits 228, 662; overlay 769)",
			"Arizona: Phoenix (see 520; also Phoenix split 480, 623)", "New Hampshire",
			"Canada: British Columbia: Greater Vancouver (overlay 778, perm 11/3/01; see 250)", "South Dakota",
			"E Kentucky: area east of Frankfort: Ashland (see 859)", "S Cent. New York: Ithaca, Binghamton; Catskills",
			"SW Wisconsin: Madison", "S New Jersey: Trenton (see 856)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (see overlays 484, 835)",
			"Reserved for special applications",
			"Cent. Minnesota: Minneapolis (split from St. Paul, see 651; see splits 763, 952)",
			"Canada: SE Ontario: Ottawa (see overlay 343)", "SE Ohio: Columbus (see overlay 380)",
			"Northern Middle Tennessee: Nashville metro area (see 423, 931; see overlay 629, eff 2014)",
			"W Michigan: Holland, Grand Haven, Greenville, Grand Rapids, Ionia (see split 269)",
			"Massachusetts: greater Boston (see overlay 857)", "S Illinois: Centralia",
			"S California: San Diego (see split 760; overlay 858, 935)",
			"S Kansas: Wichita (split from 316; perm 2/3/01)",
			"Arizona: West Phoenix (see 520; also Phoenix split 480, 602)",
			"E S California: Pasadena (split from 818 Los Angeles)",
			"No longer in use [was Napa, Sonoma counties (perm 10/13/01, mand 4/13/02); now 707]",
			"California: San Francisco County and Marin County on the north side of the Golden Gate Bridge, extending north to Sonoma County (overlaid on 415, eff 2/2015)",
			"Northern Middle Tennessee: Nashville metro area (see 423, 931; overlaid on 615, eff 2014)",
			"W NE Illinois, western suburbs of Chicago (part of what used to be 708; overlay 331)",
			"New York: Suffolk County, Long Island; Huntington, Riverhead (split 516)",
			"Missouri: W St. Louis metro area of St. Louis county, St. Charles County, Jefferson County area south (between 314 and 573)",
			"Canada: Saskatchewan (overlaid on 306)",
			"Iowa: Mason City, Marshalltown, Creston, Ottumwa (split from 515; perm 7/9/00)",
			"New York (overlaid on 212, 332, 917) NYC (mostly mobile)",
			"Canada: S Cent. Ontario: Toronto (overlaid on 416)", "Turks & Caicos Islands",
			"California: Peninsula south of San Francisco -- San Mateo County, parts of Santa Clara County (split from 415)",
			"Cent. Minnesota: St. Paul (split from Minneapolis, see 612)",
			"Northern and western Orange County (overlaid on 714)", "N Missouri (split from 816)",
			"California: N Los Angeles, Mckittrick, Mojave, Newhall, Oildale, Palmdale, Taft, Tehachapi, Bakersfield, Earlimart, Lancaster (split from 805)",
			"N Mississippi: Tupelo, Grenada (split from 601)", "Montserrat (split from 809)",
			"E Maryland: Baltimore, Annapolis, Chesapeake Bay area, Ocean City (overlaid on 410, 443)",
			"Cent. Coastal California: San Jose (overlaid on 408; eff 10/20/2012)",
			"Commonwealth of the Northern Mariana Islands (CNMI, US Commonwealth)", "Guam",
			"N Georgia: metropolitan Atlanta (overlay; see 404, 770)",
			"Michigan: Dearborn area (overlaid on 313; assigned but not in use)", "West Virginia (overlaid on 304)",
			"Texas: Fort Worth areas (perm 10/7/00, mand 12/9/00)", "American Samoa",
			"Central Florida: Metro Orlando (see overlay 321; overlaid on 407, assigned but not in use)",
			"Interexchange Carrier Services", "North Dakota",
			"S. Nevada: Clark County, incl Las Vegas (overlay 725, eff 6/2014; see also 775)",
			"Northern Virginia: Arlington, McLean, Tysons Corner (see split 540; overlay 571)",
			"W North Carolina: Charlotte (see split 828, overlay 980)",
			"Canada: NE Ontario: Sault Ste. Marie/N Ontario: N Bay, Sudbury",
			"N Georgia: Columbus, Augusta (see overlay 762)",
			"NW California: Santa Rosa, Napa, Vallejo, American Canyon, Fairfield",
			"Illinois: southern and western suburbs of Chicago (see 630; overlay 464)",
			"Canada: Newfoundland and Labrador", "US Government", "Telecommunications Relay Services",
			"W Iowa: Council Bluffs", "Mid SE Texas: central Houston (split 281; overlay 346, 832)",
			"Northern and western Orange County (see split 949, overlay 657)",
			"N Wisconsin: Eau Claire, Wausau, Superior", "NW New York: Buffalo (see split 585)",
			"E Pennsylvania: Harrisburg (see split 570, overlay 223)",
			"New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 929)",
			"SE Colorado: Pueblo, Colorado Springs", "Central Colorado: Denver (overlaid on 303)",
			"Sint Maarten (used to be country code +599)",
			"SW Pennsylvania (areas outside metro Pittsburgh; split from 412)",
			"S. Nevada: Clark County, incl Las Vegas (overlaid on 702, eff 6/2014; see also 775)",
			"Florida Tampa Metro: Saint Petersburg, Clearwater (Pinellas and parts of Pasco County; split from 813)",
			"W Tennessee: outside Memphis metro area (split from 901, perm 2/12/01, mand 9/17/01)",
			"Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 848)",
			"SE Michigan: west and south of Detroit -- Ann Arbor, Monroe (split from 313)",
			"S Texas: Austin (overlaid on 512, suspended; see also 361)",
			"SE and Central Ohio (outside Columbus; split from 614; overlay 220)",
			"Cent. North Carolina: Greensboro, Winston-Salem, High Point (overlaid on 336)",
			"S California: Los Angeles, Agoura Hills, Calabasas, Hidden Hills, and Westlake Village (see 818; implementation suspended)",
			"Florida: Broward County area, incl Ft. Lauderdale (overlaid on 954; perm 8/1/01, mand 9/1/01)",
			"E Virginia: Tidewater / Hampton Roads area -- Norfolk, Virginia Beach, Chesapeake, Portsmouth, Hampton, Newport News, Suffolk (part of what used to be 804)",
			"St. Lucia (split from 809)",
			"California: San Diego North County to Sierra Nevada (split from 619; see overlay 442)",
			"N Georgia: Columbus, Augusta (overlaid on 706)",
			"Minnesota: Minneapolis NW (split from 612; see also 952)", "(overlay on 650; SUSPENDED)",
			"Indiana: outside Indianapolis (split from 317)", "Dominica (split from 809)",
			"Mississippi: Meridian, Jackson area (overlaid on 601; perm 7/19/04, mand 3/14/05)",
			"Georgia: Atlanta suburbs: outside of I-285 ring road (part of what used to be 404; see also overlay 678)",
			"S. Central Florida: St. Lucie, Martin, and Indian River counties (split from 561; eff 2/11/02; mand 11/11/02)",
			"Illinois: city of Chicago, outside the loop (see 312; overlay 872)",
			"Cent. Massachusetts: Framingham; Cape Cod (see split 978, overlaid on 508, eff 4/2/01)",
			"N. Nevada: Reno (all of NV except Clark County area; see 702)",
			"Canada: British Columbia: Greater Vancouver (overlaid on 604, per 11/3/01; see also 250)",
			"NW Illinois: Rockford, Kankakee (overlaid on 815; eff 8/19/06, mand 2/17/07)",
			"Canada: Northern Alberta, north of Lacombe (see 403, 587, 825)",
			"Massachusetts: Boston surburbs, to the north and west (see splits 617, 508; overlay 339)",
			"Nova Scotia & Prince Edward Island (to be overlaid on 902, eff 11/30/14)",
			"St. Vincent & Grenadines (split from 809)", "N & W Kansas: Topeka (split from 913)",
			"SE Florida, Monroe County (Miami; overlaid on 305)", "Puerto Rico (see overlay 939, perm 8/1/01)",
			"US/Canada toll free (see 888, 877, 866, 855, 844, 833, 822)",
			"Utah: Salt Lake City Metro (see split 385, eff 3/30/02; see also split 435)", "Vermont",
			"South Carolina: Columbia, Aiken, Sumter (see 843, 864)", "E Virginia: Richmond (see splits 757, 434)",
			"S Cent. and Cent. Coastal California: Ventura County, Santa Barbara County: San Luis Obispo, Thousand Oaks, Carpinteria, Santa Barbara, Santa Maria, Lompoc, Santa Ynez Valley / Solvang (see 661 split)",
			"Panhandle Texas: Amarillo, Lubbock", "Canada: W Ontario: Thunder Bay region to Manitoba border", "Hawaii",
			"Dominican Republic (see splits 264, 268, 284, 340, 441, 473, 664, 758, 767, 784, 868, 876; overlay 829)",
			"E Michigan: Flint, Pontiac (see 248; split 586)", "Reserved for special applications",
			"S Indiana: Evansville, Cincinnati outskirts in IN, Columbus, Bloomington (mostly GMT-5)",
			"SW Florida: Tampa Metro (splits 727 St. Petersburg, Clearwater, and 941 Sarasota)",
			"Cent. Pennsylvania: Erie", "NW Illinois: Rockford, Kankakee (see overlay 779; eff 8/19/06, mand 2/17/07)",
			"N Missouri: Kansas City (see split 660, overlay 975)", "N Cent. Texas: Fort Worth area (see 254, 940)",
			"S California: Los Angeles: San Fernando Valley (see 213, 310, 562, 626, 747)",
			"NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (see split 867; see overlay 873)",
			"US/Canada toll free (proposed, may not be in use yet)", "Alberta (overlay; see 403, 587, 780)",
			"W North Carolina: Asheville (split from 704)",
			"Dominican Republic (perm 1/31/05; mand 8/1/05; overlaid on 809)",
			"Texas: region surrounding San Antonio (split from 210)",
			"California: central coast area from Santa Cruz through Monterey County",
			"Texas: Houston (overlay 713, 281, 346)", "US/Canada toll free (proposed, may not be in use yet)",
			"SE Pennsylvania: Allentown, Bethlehem, Reading, West Chester, Norristown (overlaid on 610, eff 5/1/01; see also 484)",
			"South Carolina, coastal area: Charleston, Beaufort, Myrtle Beach (split from 803)",
			"US/Canada toll free (proposed, may not be in use yet)",
			"New York: Poughkeepsie; Nyack, Nanuet, Valley Cottage, New City, Putnam, Dutchess, Rockland, Orange, Ulster and parts of Sullivan counties in New York's lower Hudson Valley and Delaware County in the Catskills (see 914; perm 6/5/00)",
			"Northern NE Illinois: northwestern suburbs of chicago (Evanston, Waukegan, Northbrook; see overlay 224)",
			"Cent. New Jersey: Toms River, New Brunswick, Bound Brook (see overlay 732)",
			"Dominican Republic: Santo Domingo",
			"Florida panhandle, from east of Tallahassee to Pensacola (split from 904); western panhandle (Pensacola, Panama City) are UTC-6",
			"US/Canada toll free", "SW New Jersey: greater Camden area, Mt Laurel (split from 609)",
			"Massachusetts: greater Boston (overlaid on 617, eff 4/2/01)",
			"S California: San Diego (see split 760; overlay 619, 935)",
			"N and Central Kentucky: Lexington; suburban KY counties of Cincinnati OH metro area; Covington, Newport, Ft. Thomas, Ft. Wright, Florence (split from 606)",
			"Connecticut: areas outside of Fairfield and New Haven Counties (split from 203, overlay 959)",
			"N New Jersey: Newark Paterson Morristown (overlaid on 973)",
			"Florida: Lakeland, Polk County (split from 941)",
			"South Carolina, upstate area: Greenville, Spartanburg (split from 803)",
			"E Tennessee: Knoxville, Knox and adjacent counties (split from 423; part of what used to be 615)",
			"US/Canada toll free", "Canada: Yukon, Northwest Territories, Nunavut (split from 403/819)",
			"Trinidad and Tobago (\"new\" -- see 809)", "St. Kitts & Nevis",
			"Arkansas: areas outside of west/central AR: Jonesboro, etc",
			"Illinois: Chicago (downtown only -- in the loop; see 773; overlaid on 312 and 773)",
			"NW Quebec: Trois Rivieres, Sherbrooke, Outaouais (Gatineau, Hull), and the Laurentians (up to St Jovite / Tremblant) (overlaid on 819)",
			"Jamaica (split from 809)", "US/Canada toll free",
			"Pittsburgh, New Castle (overlaid on 412, perm 8/17/01, mand t.b.a.)", "Paid Toll-Free Service",
			"Paid Toll-Free Service", "Paid Toll-Free Service", "US/Canada toll free", "VoIP service",
			"US toll calls -- prices vary with the number called",
			"W Tennessee: Memphis metro area (see 615, 931, split 731)",
			"Canada: Nova Scotia, Prince Edward Island (see overlay 782)",
			"NE Texas: Tyler (see overlay 430, eff 7/20/02)", "N Florida: Jacksonville (see splits 352, 386, 850)",
			"Canada: S Cent. Ontario: Greater Toronto Area -- Durham, Halton, Hamilton-Wentworth, Niagara, Peel, York, and southern Simcoe County (excluding Toronto -- see overlay 289, 365, splits 416, 647)",
			"Upper Peninsula Michigan: Sault Ste. Marie, Escanaba, Marquette (UTC-6 towards the WI border)", "Alaska",
			"Cent. New Jersey: Elizabeth, Basking Ridge, Somerville, Bridgewater, Bound Brook",
			"California: Inland empire: San Bernardino (see split 951), Riverside",
			"S Cent. North Carolina: Fayetteville, Wilmington (see 336)", "Emergency",
			"SE Georgia: Savannah (see splits 229, 478)", "Kansas: Kansas City area (see 785)",
			"S New York: Westchester County (see 845)", "W Texas: El Paso (see splits 325 eff 4/5/03; 432, eff 4/5/03)",
			"NE California: Sacramento, Walnut Grove, Lincoln, Newcastle and El Dorado Hills (split to 530)",
			"New York: New York City (cellular, see 646)", "E Oklahoma: Tulsa (see overlay 539)",
			"E North Carolina: Raleigh (see split 252, overlay 984)",
			"NE Wisconsin: Appleton, Green Bay, Sheboygan, Fond du Lac (from Beaver Dam NE to Oshkosh, Appleton, and Door County; part of what used to be 414)",
			"California: Contra Costa area: Antioch, Concord, Pleasanton, Walnut Creek (split from 510)",
			"Florida: Cellular coverage in Orlando area",
			"Central and Northern Arizona: Prescott, Flagstaff, Yuma (split from 520)",
			"New York City, New York (Queens, Staten Island, The Bronx, and Brooklyn; also Marble Hill section of Manhattan; see split 212, 347, 718)",
			"Middle Tennessee: semi-circular ring around Nashville (split from 615)",
			"S California: San Diego (see split 760; overlay 858, 619; assigned but not in use)",
			"SE Texas: Conroe, Lufkin, Nacogdoches, Crockett (split from 409, see also 979)",
			"SW Ohio: Dayton (part of what used to be 513)", "Puerto Rico (overlaid on 787, perm 8/1/01)",
			"N Cent. Texas: Denton, Wichita Falls (split from 254, 817)",
			"SW Florida: Sarasota and Manatee counties (part of what used to be 813; see split 863)",
			"Michigan: Oakland County (overlays 248, perm 5/5/01)",
			"California: S Coastal Orange County (split from 714)",
			"California: W Riverside County (split from 909; eff 7/17/04)",
			"Minnesota: Minneapolis SW, Bloomington (split from 612; see also 763)",
			"Florida: Broward County area, incl Ft. Lauderdale (part of what used to be 305, see overlay 754)",
			"Texas: Valley of Texas area; Harlingen, Laredo (split from 210)", "New Mexico (pending; region unknown)",
			"Connecticut: Hartford, New London (postponed; was overlaid on 860 perm 1/6/01; mand 3/1/01???)",
			"N and W Colorado (part of what used to be 303)",
			"Oregon: Metropolitan Portland, Salem/Keizer area, incl Cricket Wireless (see 503; perm 10/1/00)",
			"Texas: Dallas Metro (overlays 214/469)",
			"N New Jersey: Newark, Paterson, Morristown (see overlay 862; split from 201)",
			"N Missouri: Kansas City (overlaid on 816)", "Unassigned",
			"Massachusetts: north of Boston to NH (see split 978 -- this is the northern half of old 508; see overlay 351)",
			"SE Texas: Bryan, College Station, Bay City (split from 409, see also 936)",
			"North Carolina: (overlay on 704; perm 5/1/00, mand 3/15/01)",
			"E North Carolina: Raleigh (overlaid on 919, perm 8/1/01, mand 2/5/02 POSTPONED)",
			"E Louisiana: SE/N shore of Lake Pontchartrain: Hammond, Slidell, Covington, Amite, Kentwood, area SW of New Orleans, Houma, Thibodaux, Morgan City (split from 504; perm 2/12/01; mand 10/22/01)",
			"Upper central Michigan: Mt Pleasant, Saginaw (split from 517; perm 4/7/01)", "" };

	public AreaCodeListing() {
	}

	public String[] getValidCodes() {
		return validCodes;
	}

	public String[] getValidDesc() {
		return validDesc;
	}
}
